### ISSUE TITLE
Joining the server.

### ISSUE THREAD

**Issue by Christopher111111111** [SmartlyDressedGames/Unturned-Docs#51]
I am, again, sorry, me and another person have been troubleshooting and trying things from changing the password to giving admin ship to them and they cannot connect. It says that it is trying to connect but is unable to connect.

**Comment by SDGNelson** [comment]
If they get "unable to find server" then most likely port forwarding is incorrect: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/PortForwarding.md

**Comment by Christopher111111111** [comment]
It is a LAN server

**Comment by MoltonMontro** [comment]
> It is a LAN server

Are they on the same network as you? Other people cannot join a LAN server unless they're on the same network as you. If they're not on the same network as you, you should host a dedicated (port forwarded) server.

If you're currently trying to use virtual LAN software to emulate LAN gaming, then you should refer to setup documentation that they provide.

**Comment by Christopher111111111** [comment]
We were on the same wifi/network, so it is not the fact that we were not on the same network
I can try to make an internet server and see if that works

**Comment by MeblIkea** [comment]
I have the exact same problem, I host the server on my computer, and when I try to join it (with `+LanServer/`), it said `Lost connection to host or Steam network.`
Any idea?

**Comment by SDGNelson** [comment]
Can you share the Server_ (id) .log file from your U3DS/Logs folder please Mebllkea?

**Comment by MeblIkea** [comment]
> Can you share the Server_ (id) .log file from your U3DS/Logs folder please Mebllkea?

Here it is

[Server_LeServDesBG.log](https://github.com/SmartlyDressedGames/U3-Docs/files/8061273/Server_LeServDesBG.log)

**Comment by SDGNelson** [comment]
Fortunately (or perhaps unfortunately) everything seems to be starting up properly. In part I had wondered if it was failing to get the SNS certificates but that looks to be working fine.

About a month ago there was a problem where steam_appid.txt seemed to get an extra zero (still no idea *why*, but made the game paranoid about it) - I do not think this is the problem here, but it might be worth checking the steam_appid.txt file in the U3DS folder to see whether it is the correct value: 304930

After trying to connect and it fails, if you could send me the Client.log file from the Unturned/Logs folder there *might* be an error there, but less likely.

**Comment by MeblIkea** [comment]
Thanks for the answer, but anyway, I just bought a server on pingperfect.com, and it work fine

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
